app/views/govuk_wrapper.scala.html, app/views/helpers/phaseBanner.scala.html
SAR-138: Added BETA banner at top of screens.
=> SAR-138: Added BETA banner at top of screens.

app/views/business/accounting_period.scala.html, conf/messages, test/assets/MessageLookup.scala, test/views/business/BusinessAccountingPeriodViewSpec.scala
The
> Where can I get this information
accordion
=> added accordion on business accounting period view

app/views/business/income_type.scala.html, app/views/helpers/radioHelper.scala.html, app/views/html/helpers/RadioOption.scala, conf/messages, test/views/business/BusinessIncomeTypeViewSpec.scala, test/views/helpers/RadioHelperSpec.scala
refactored the radio helper to separate the text displayed from the id and value of the inputs
=> Radio refactor

app/controllers/business/CurrentFinancialPeriodPriorController.scala, app/forms/CurrentFinancialPeriodPriorForm.scala, app/models/CurrentFinancialPeriodPriorModel.scala, app/services/KeystoreService.scala, app/views/business/current_financial_period_prior.scala.html, conf/business.routes, conf/messages, test/assets/MessageLookup.scala, test/controllers/business/CurrentFinancialPeriodPriorControllerSpec.scala, test/routes/RoutesSpec.scala, test/services/mocks/MockKeystoreService.scala, test/views/business/BusinessCurrentFinancialPeriodPriorViewSpec.scala
-- Has TODO around the post actions for the 'Yes' route as this is dependant on a future task. SAR-403.
=> SAR-402: Added the 'current financial period prior to april 2017' page

app/controllers/business/RegisterNextAccountingPeriodController.scala, app/forms/RegisterNextAccountingPeriodForm.scala, app/models/RegisterNextAccountingPeriodModel.scala, app/services/CacheConstants.scala, app/services/KeystoreService.scala, app/views/business/register_next_accounting_period.scala.html, app/views/summary_page.scala.html, conf/business.routes, conf/messages, test/assets/MessageLookup.scala, test/controllers/business/RegisterNextAccountingPeriodControllerSpec.scala, test/forms/CurrentFinancialPeriodPriorFormSpec.scala, test/forms/RegisterNextAccountingPeriodFormSpec.scala, test/forms/validation/testutils/DataMap.scala, test/routes/RoutesSpec.scala, test/services/mocks/MockKeystoreService.scala, test/views/business/BusinessCurrentFinancialPeriodPriorViewSpec.scala, test/views/business/BusinessRegisterNextAccountingPeriodViewSpec.scala
- Also corrected some test typos on Current Financial Period Prior as well as adding missing test for the form.
=> SAR-403: Added 'register-next-accounting-period' page

app/auth/AuthorisedForIncomeTaxSA.scala, app/controllers/AlreadyEnrolledController.scala, app/controllers/ErrorPageRenderer.scala, test/auth/AuthTestController.scala, test/controllers/AlreadyEnrolledControllerSpec.scala, test/controllers/ConfirmationControllerSpec.scala, test/controllers/ErrorPageRendererSpec.scala
bug fix for already enrolled controller to prevent incorrect redirections.
also added error page renderer
=> bug fix for already enrolled controller

app/models/auth/UserIds.scala, conf/logback-test.xml, it/controllers/HomeControllerISpec.scala, it/helpers/ComponentSpecBase.scala, it/helpers/CustomMatchers.scala, it/helpers/ImplicitConversions.scala, it/helpers/IntegrationTestConstants.scala, it/helpers/SessionCookieBaker.scala, it/helpers/WiremockHelper.scala, it/helpers/servicemocks/AuditStub.scala, it/helpers/servicemocks/AuthStub.scala, it/helpers/servicemocks/WireMockMethods.scala, project/MicroService.scala
ported the latest component test framework from the protected microservice
=> SAR-695: component test framework update

it/controllers/HomeControllerISpec.scala
=> Added component tests

app/config/ExcludingCSRFFilter.scala, app/config/frontendGlobal.scala, app/testonly/controllers/PreferenceTokenController.scala, app/testonly/models/preferences/AddTokenRequest.scala, app/testonly/models/preferences/AddTokenResponse.scala, conf/testOnlyDoNotUseInAppConf.routes
also added csrf exception filter for this route
=> SAR-994: added test only route to add preferences token

app/core/views/helpers/dateHelper.scala.html, app/core/views/helpers/inputHelper.scala.html, conf/application.conf
and conformed date helper to gov uk standards
=> updated to the latest assets frontend 

conf/messages.cy
Reverts hmrc/income-tax-subscription-frontend#421
=> Revert "SAR-2262 - Made the changes specifed by the welsh translation team th…"

app/core/views/html/helpers/SummaryHelper.scala, app/core/views/html/helpers/SummaryIdConstants.scala, app/incometax/subscription/services/SubscriptionService.scala, app/incometax/subscription/views/check_your_answers.scala.html, app/incometax/util/AccountingPeriodUtil.scala, conf/messages, conf/messages.cy, it/helpers/servicemocks/SubscriptionStub.scala, test/assets/MessageLookup.scala, test/core/services/CacheUtilSpec.scala, test/core/utils/TestModels.scala, test/incometax/subscription/services/SubscriptionServiceSpec.scala, test/incometax/subscription/views/CheckYourAnswersViewSpec.scala
also updated the submission service
=> SAR-4730 Update to CYA to include new answer

app/agent/controllers/business/BusinessAccountingMethodController.scala, app/agent/controllers/business/MatchTaxYearController.scala, it/agent/controllers/business/MatchTaxYearControllerISpec.scala, test/agent/controllers/business/BusinessAccountingMethodControllerSpec.scala, test/agent/controllers/business/MatchTaxYearControllerSpec.scala
=> SAR-4967 Modified routing to include new WhatTaxYear page for agents.

app/controllers/agent/IncomeSourceController.scala, app/controllers/agent/business/BusinessAccountingMethodController.scala, app/controllers/agent/business/PropertyAccountingMethodController.scala, app/controllers/agent/business/PropertyCommencementDateController.scala, it/controllers/agent/IncomeSourceControllerISpec.scala, it/controllers/agent/business/BusinessAccountingMethodControllerISpec.scala, test/controllers/agent/IncomeSourceControllerSpec.scala, test/controllers/agent/business/BusinessAccountingMethodControllerSpec.scala, test/controllers/agent/business/PropertyCommencementDateControllerSpec.scala, test/controllers/agent/business/UkPropertyAccountingMethodControllerSpec.scala
Reverts hmrc/income-tax-subscription-frontend#675
=> Revert "MISUV-991 Update flow for Agent UK Property"

app/controllers/agent/IncomeSourceController.scala, app/controllers/agent/business/BusinessAccountingMethodController.scala, app/controllers/agent/business/PropertyAccountingMethodController.scala, app/controllers/agent/business/PropertyCommencementDateController.scala, it/controllers/agent/IncomeSourceControllerISpec.scala, it/controllers/agent/business/BusinessAccountingMethodControllerISpec.scala, test/controllers/agent/IncomeSourceControllerSpec.scala, test/controllers/agent/business/BusinessAccountingMethodControllerSpec.scala, test/controllers/agent/business/PropertyCommencementDateControllerSpec.scala, test/controllers/agent/business/UkPropertyAccountingMethodControllerSpec.scala
Reverts hmrc/income-tax-subscription-frontend#677
=> Revert "Revert "MISUV-991 Update flow for Agent UK Property""

app/controllers/individual/business/OverseasPropertyCommencementDateController.scala, app/controllers/individual/incomesource/IncomeSourceController.scala, app/controllers/individual/subscription/CheckYourAnswersController.scala, app/views/individual/incometax/subscription/check_your_answers.scala.html, it/controllers/individual/incomesource/IncomeSourceControllerISpec.scala, test/controllers/agent/business/OverseasPropertyCommencementDateControllerSpec.scala, test/controllers/individual/business/OverseasPropertyCommencementDateControllerSpec.scala, test/controllers/individual/incomesource/IncomeSourceControllerSpec.scala, test/views/individual/incometax/subscription/CheckYourAnswersViewSpec.scala
=> MISUV-1060. Updated routes in IncomeSourceController, CYA view and tests

app/config/frontendAppConfig.scala, app/views/individual/incometax/subscription/check_your_answers.scala.html, test/config/MockConfig.scala, test/views/individual/incometax/subscription/CheckYourAnswersViewSpec.scala
=> MISUV-1220: correct redirect rout for business accounting method depends on ReleaseFour FS

app/config/frontendAppConfig.scala, app/controllers/SessionTimeoutController.scala, app/controllers/agent/SessionTimeoutController.scala, app/views/agent/agent_frontpage.scala.html, app/views/agent/no_sa.scala.html, app/views/agent/timeout.scala.html, app/views/individual/incometax/subscription/enrolled/already_enrolled.scala.html, app/views/individual/timeout.scala.html, app/views/individual/usermatching/no_sa.scala.html, app/views/templates/agent_main_template.scala.html, app/views/templates/govuk_wrapper.scala.html, app/views/templates/main_template.scala.html, conf/agent.routes, conf/app.routes, conf/application.conf, it/controllers/SessionTimeoutControllerISpec.scala, it/controllers/agent/SessionTimeoutControllerISpec.scala, it/helpers/ComponentSpecBase.scala, it/helpers/agent/ComponentSpecBase.scala, test/config/MockConfig.scala, test/controllers/SessionTimeoutControllerSpec.scala, test/controllers/agent/SessionTimeoutControllerSpec.scala, test/utilities/UnitTestTrait.scala, test/views/MainTemplateViewSpec.scala, test/views/agent/NoSAViewSpec.scala, test/views/individual/usermatching/NoSAViewSpec.scala
=> ITSASU-165

app/controllers/individual/business/WhatYearToSignUpController.scala, it/controllers/individual/business/WhatYearToSignUpControllerISpec.scala, it/helpers/IntegrationTestConstants.scala, test/controllers/individual/business/WhatYearToSignUpControllerSpec.scala
Update select tax year page routing.
=> ITSASU-417: Update select tax year page routing

app/controllers/individual/business/ProgressSavedController.scala, app/views/individual/incometax/business/ProgressSaved.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/individual/business/ProgressSavedControllerISpec.scala, it/helpers/ComponentSpecBase.scala, test/assets/MessageLookup.scala, test/controllers/individual/business/ProgressSavedControllerSpec.scala, test/views/individual/incometax/business/ProgressSavedViewSpec.scala
=> ITSASU-441: Create save progress page

app/views/individual/incometax/business/TaskList.scala.html, test/views/individual/incometax/business/TaskListViewSpec.scala
Update Sole trader business link:
* Add editMode query param
* Add Sole trader business ID query param
=> ITSASU-530: Update TaskList

app/models/common/PropertyModel.scala, app/services/SubscriptionDetailsService.scala, app/utilities/SubscriptionDataKeys.scala, app/utilities/SubscriptionDataUtil.scala, test/models/common/PropertyModelSpec.scala, test/services/mocks/MockSubscriptionDetailsService.scala
=> ITSASU-551: UK Property - Check your answers Page

app/controllers/individual/PreferencesController.scala, app/controllers/individual/sps/SPSCallbackController.scala, it/controllers/PreferencesControllerISpec.scala, it/controllers/individual/sps/SPSCallbackControllerISpec.scala, test/controllers/individual/PreferencesControllerSpec.scala, test/controllers/individual/sps/SPSCallbackControllerSpec.scala
=> ITSASU-585: Introduction to Task List Service

app/controllers/individual/business/OverseasPropertyCheckYourAnswersController.scala, app/services/SubscriptionDetailsService.scala, app/views/individual/incometax/business/OverseasPropertyCheckYourAnswers.scala.html, app/views/templates/injected/CheckYourAnswers.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/individual/business/OverseasPropertyCheckYourAnswersControllerISpec.scala, it/helpers/ComponentSpecBase.scala, it/helpers/IntegrationTestModels.scala, test/controllers/individual/business/OverseasPropertyCheckYourAnswersControllerSpec.scala, test/services/mocks/MockSubscriptionDetailsService.scala, test/views/individual/incometax/business/OverseasPropertyCheckYourAnswersViewSpec.scala, test/views/individual/incometax/business/PropertyCheckYourAnswersViewSpec.scala
=> ITSASU-597: Overseas Property CYA Page

app/config/frontendAppConfig.scala, app/controllers/individual/incomesource/WhatIncomeSourceToSignUpController.scala, app/forms/individual/incomesource/BusinessIncomeSourceForm.scala, app/forms/submapping/BusinessIncomeSourceMapping.scala, app/models/IncomeSourcesStatus.scala, app/models/common/BusinessIncomeSource.scala, app/services/SubscriptionDetailsService.scala, app/views/individual/incometax/incomesource/WhatIncomeSourceToSignUp.scala.html, conf/application.conf, conf/messages, conf/messages.cy, it/controllers/individual/incomesource/WhatIncomeSourceToSignUpControllerISpec.scala, it/helpers/ComponentSpecBase.scala, scalastyle-config.xml, test/config/MockConfig.scala, test/controllers/individual/incomesource/WhatIncomeSourceToSignUpControllerSpec.scala, test/forms/individual/incomesource/BusinessIncomeSourceFormSpec.scala, test/services/mocks/MockSubscriptionDetailsService.scala, test/views/individual/incometax/incomesource/WhatIncomeSourceToSignUpViewSpec.scala
- Updated the income source page to become dynamically populated radio buttons based on the current income sources stored for the user
- Updated form to validate against a varying list of options (including messages)
- Updated content of page
=> ITSASU-779:

app/controllers/agent/business/OverseasPropertyAccountingMethodController.scala, app/controllers/agent/business/OverseasPropertyStartDateController.scala, it/controllers/agent/business/OverseasPropertyAccountingMethodControllerISpec.scala, it/controllers/agent/business/OverseasPropertyStartDateControllerISpec.scala, it/helpers/agent/IntegrationTestConstants.scala, test/controllers/agent/business/OverseasPropertyAccountingMethodControllerSpec.scala, test/controllers/agent/business/OverseasPropertyStartDateControllerSpec.scala
=> ITSASU-806: add redirect urls for agent overseas property check your answers

app/views/agent/business/TaxYearCheckYourAnswers.scala.html, test/views/agent/business/TaxYearCheckYourAnswersViewSpec.scala
=> ITSASU-757: Fix Agent TaxYear CYA change link

app/controllers/agent/business/PropertyStartDateController.scala, app/controllers/individual/business/PropertyStartDateController.scala, app/views/agent/business/PropertyStartDate.scala.html, app/views/helpers/injected/SaveAndContinueButtonHelper.scala.html, app/views/individual/incometax/business/PropertyStartDate.scala.html, test/controllers/agent/business/PropertyStartDateControllerSpec.scala, test/views/agent/business/UkPropertyStartDateViewSpec.scala, test/views/individual/incometax/business/UkPropertyStartDateViewSpec.scala, test/views/individual/mocks/MockPropertyStartDate.scala
Update content and redirect routes
=> ITSASU-812: UK property start date

app/views/agent/business/PropertyAccountingMethod.scala.html, test/agent/assets/MessageLookup.scala, test/views/agent/business/UkPropertyAccountingMethodViewSpec.scala
- When S&R F/S enabled, continue button becomes save & continue, save & come back later buttons.
- Added tests to test added functionality to the view
=> ITSASU-814 - updated uk property accounting method page content

app/controllers/agent/business/OverseasPropertyAccountingMethodController.scala, app/views/agent/business/OverseasPropertyAccountingMethod.scala.html, test/views/agent/business/OverseasPropertyAccountingMethodViewSpec.scala
=> ITSASU-819: Agent Overseas Property - Accounting Method Page

app/views/individual/incometax/business/TaxYearCheckYourAnswers.scala.html, conf/messages, conf/messages.cy, test/views/individual/incometax/business/TaxYearCheckYourAnswersViewSpec.scala
=> ITSASU-846: Missing Welsh for Save and retrieve journey

app/views/agent/AgentTaskList.scala.html, app/views/individual/incometax/business/TaskList.scala.html, test/views/agent/AgentTaskListViewSpec.scala, test/views/individual/incometax/business/TaskListViewSpec.scala
=> ITSASU-888: Correct Tax Year CYA link in Task List page

it/controllers/agent/eligibility/OtherSourcesOfIncomeControllerISpec.scala, it/controllers/agent/eligibility/PropertyTradingStartAfterControllerISpec.scala, it/controllers/agent/eligibility/SoleTraderControllerISpec.scala, project/FrontendBuild.scala
This appears to be all that is needed...?!
=> [ITSASU-908] Convert to newer Play HMRC Frontend library, version 3.0.0

app/controllers/agent/WhatIncomeSourceToSignUpController.scala, app/controllers/agent/business/OverseasPropertyStartDateController.scala, app/controllers/agent/business/PropertyStartDateController.scala, app/forms/agent/BusinessIncomeSourceForm.scala, app/forms/agent/submapping/BusinessIncomeSourceMapping.scala, app/forms/formatters/NewDateModelMapping.scala, app/forms/individual/business/PropertyStartDateForm.scala, app/views/agent/AgentTaskList.scala.html, app/views/agent/WhatIncomeSourceToSignUp.scala.html, build.sbt, conf/agent.routes, conf/messages, conf/messages.cy, it/connectors/stubs/IncomeTaxSubscriptionConnectorStub.scala, it/controllers/agent/WhatIncomeSourceToSignUpControllerISpec.scala, it/helpers/agent/ComponentSpecBase.scala, test/controllers/agent/WhatIncomeSourceToSignUpControllerSpec.scala, test/controllers/agent/business/OverseasPropertyStartDateControllerSpec.scala, test/controllers/agent/business/PropertyStartDateControllerSpec.scala, test/forms/agent/BusinessIncomeSourceFormSpec.scala, test/views/agent/AgentTaskListViewSpec.scala, test/views/agent/WhatIncomeSourceToSignUpViewSpec.scala, test/views/individual/mocks/MockRemoveUkProperty.scala
=> ITSASU-952: Agent - Create the "Add a business" page

app/controllers/agent/business/RemoveBusinessController.scala, app/forms/agent/RemoveBusinessForm.scala, app/views/agent/business/RemoveBusiness.scala.html, conf/agent.routes, conf/messages, conf/messages.cy, it/controllers/agent/business/RemoveBusinessControllerISpec.scala, it/helpers/agent/ComponentSpecBase.scala, test/controllers/agent/business/RemoveBusinessControllerSpec.scala, test/views/agent/business/RemoveBusinessViewSpec.scala
=> ITSASU-946: Agent - Sole Trader - Confirmation page for removal

conf/messages.cy
=> ITSASU-952: Add missing Welsh

app/models/common/TaskListModel.scala, app/views/agent/AgentTaskList.scala.html, app/views/individual/incometax/business/TaskList.scala.html, test/models/common/TaskListModelSpec.scala
Remove hard-coded sole trader businesses limit from TaskListModel.
=> ITSASU-992: Task list page - Update add business link (Individual/agent)

README.md, scripts/start
Bring README into line and add start script in script directory
=> [ITSASU-954] 

app/controllers/agent/business/ClientRemoveUkPropertyController.scala, app/models/UpdateDeadlineDates.scala, app/services/AccountingPeriodService.scala, app/views/agent/business/WhatYearToSignUp.scala.html, app/views/helpers/injected/UpdateDeadlineTable.scala.html, app/views/individual/incometax/business/WhatYearToSignUp.scala.html, app/views/individual/incometax/subscription/SignUpComplete.scala.html, conf/messages, conf/messages.cy, it/controllers/individual/business/WhatYearToSignUpControllerISpec.scala, test/assets/MessageLookup.scala, test/views/agent/business/WhatYearToSignUpViewSpec.scala, test/views/individual/incometax/business/WhatYearToSignUpViewSpec.scala, test/views/individual/incometax/subscription/SignUpCompleteViewSpec.scala
- Update Choose a tax year pages
=> ITSASU-997: Add in quarterly submission dates

app/controllers/usermatching/HomeController.scala, app/services/PrePopulationService.scala, test/controllers/usermatching/HomeControllerSpec.scala, test/services/PrePopulationServiceSpec.scala, test/services/mocks/MockPrePopulationService.scala, test/services/mocks/MockSubscriptionDetailsService.scala
Extract prepop persistence to its own service
Split out tests
=> [ITSASU-963] Extract prepop persistence to its own service

conf/messages, conf/messages.cy, test/views/agent/SignUpCompleteViewSpec.scala
=> Update agent confirmation page header

app/views/agent/business/OverseasPropertyAccountingMethod.scala.html, app/views/agent/business/PropertyAccountingMethod.scala.html
=> ITSASU-1020: Accounting Method page - update radio button layout

app/forms/agent/ClientDetailsForm.scala, app/forms/agent/OverseasPropertyStartDateForm.scala, app/forms/agent/PropertyStartDateForm.scala, app/forms/formatters/DateErrorMapping.scala, app/forms/formatters/DateModelMapping.scala, app/forms/formatters/DateValidation.scala, app/forms/individual/business/OverseasPropertyStartDateForm.scala, app/forms/individual/business/PropertyStartDateForm.scala, app/forms/usermatching/UserDetailsForm.scala, app/views/helpers/injected/DateHelper.scala.html, conf/messages, conf/messages.cy, test/controllers/agent/matching/ClientDetailsControllerSpec.scala, test/controllers/usermatching/UserDetailsControllerSpec.scala, test/forms/agent/ClientDetailsFormSpec.scala, test/forms/agent/OverseasPropertyStartDateFormSpec.scala, test/forms/agent/PropertyStartDateFormSpec.scala, test/forms/formatters/DateErrorMappingSpec.scala, test/forms/formatters/DateModelFormatterSpec.scala, test/forms/formatters/DateModelMappingTest.scala, test/forms/formatters/DateValidationSpec.scala, test/forms/individual/business/OverseasPropertyStartDateFormSpec.scala, test/forms/individual/business/PropertyStartDateFormSpec.scala, test/forms/usermatching/UserDetailsFormSpec.scala, test/views/agent/business/OverseasPropertyStartDateViewSpec.scala, test/views/agent/business/UkPropertyStartDateViewSpec.scala, test/views/individual/incometax/business/OverseasPropertyStartDateViewSpec.scala, test/views/individual/incometax/business/UkPropertyStartDateViewSpec.scala, test/views/individual/usermatching/UserDetailsViewSpec.scala
=> ITSASU-1073: Improve date mapping

app/views/agent/business/OverseasPropertyCheckYourAnswers.scala.html, app/views/agent/business/PropertyCheckYourAnswers.scala.html, app/views/individual/incometax/business/OverseasPropertyCheckYourAnswers.scala.html, app/views/individual/incometax/business/PropertyCheckYourAnswers.scala.html, conf/messages, conf/messages.cy, test/views/agent/business/OverseasPropertyCheckYourAnswersViewSpec.scala, test/views/agent/business/PropertyCheckYourAnswersViewSpec.scala, test/views/individual/incometax/business/OverseasPropertyCheckYourAnswersViewSpec.scala, test/views/individual/incometax/business/PropertyCheckYourAnswersViewSpec.scala
=> ITSASU-1094: Fix different meanings for link

app/forms/formatters/DateValidation.scala, test/forms/formatters/DateValidationSpec.scala
=> ITSASU-1072: White Space Trimming on dates

app/controllers/individual/business/TaskListController.scala, app/views/individual/incometax/business/TaskList.scala.html, test/views/individual/incometax/business/TaskListViewSpec.scala
=> ITSASU-1172: Fix Individual visual issue on task list page

app/models/audits/SaveAndComebackAuditing.scala, test/models/audits/SaveAndComeBackAuditModelSpec.scala
=> ITSASU-1228: Fix SignUpSaveAndComeBack audit event

app/config/featureswitch/FeatureSwitch.scala, test/config/featureswitch/FeatureSwitchingSpec.scala
=> ITSASU-1401: Remove Save And Retrieve feature switch

app/config/frontendAppConfig.scala, app/connectors/MandationStatusConnector.scala, app/connectors/httpparser/PostMandationStatusParser.scala, app/controllers/agent/matching/ConfirmClientController.scala, app/controllers/usermatching/HomeController.scala, app/models/ErrorModel.scala, app/models/status/MandationStatus.scala, app/models/status/MandationStatusModel.scala, app/models/status/MandationStatusRequest.scala, app/services/MandationStatusService.scala, app/services/SubscriptionDetailsService.scala, app/utilities/SubscriptionDataKeys.scala, it/connectors/MandationStatusConnectorISpec.scala, it/controllers/agent/matching/ConfirmClientControllerISpec.scala, it/controllers/usermatching/HomeControllerISpec.scala, it/helpers/servicemocks/MandationStatusStub.scala, test/config/MockConfig.scala, test/connectors/MandationStatusConnectorSpec.scala, test/connectors/httpparser/PostMandationStatusParserSpec.scala, test/controllers/agent/matching/ConfirmClientControllerSpec.scala, test/controllers/usermatching/HomeControllerSpec.scala, test/models/status/MandationStatusModelSpec.scala, test/models/status/MandationStatusRequestSpec.scala, test/services/MandationStatusServiceSpec.scala, test/services/mocks/MockMandationStatusConnector.scala, test/services/mocks/MockMandationStatusService.scala, test/services/mocks/MockSubscriptionDetailsService.scala, test/services/mocks/MockUserLockoutService.scala
=> ITSASU-1454: Integrate with ITSA Status API connection

app/config/featureswitch/FeatureSwitch.scala, app/controllers/agent/matching/ConfirmClientController.scala, app/controllers/usermatching/HomeController.scala, conf/application.conf, it/controllers/agent/matching/ConfirmClientControllerISpec.scala, it/controllers/usermatching/HomeControllerISpec.scala, test/controllers/agent/matching/ConfirmClientControllerSpec.scala, test/controllers/usermatching/HomeControllerSpec.scala
=> ITSASU-1454: Add feature switch for ITSA status call

app/controllers/agent/TaxYearCheckYourAnswersController.scala, app/controllers/agent/WhatYearToSignUpController.scala, app/controllers/individual/business/TaxYearCheckYourAnswersController.scala, app/controllers/individual/business/WhatYearToSignUpController.scala, it/controllers/agent/business/TaxYearCheckYourAnswersControllerISpec.scala, it/controllers/agent/business/WhatYearToSignUpControllerISpec.scala, it/controllers/individual/business/TaxYearCheckYourAnswersControllerISpec.scala, it/controllers/individual/business/WhatYearToSignUpControllerISpec.scala, test/controllers/agent/business/TaxYearCheckYourAnswersControllerSpec.scala, test/controllers/agent/business/WhatYearToSignUpControllerSpec.scala, test/controllers/individual/business/TaxYearCheckYourAnswersControllerSpec.scala, test/controllers/individual/business/WhatYearToSignUpControllerSpec.scala, test/services/mocks/MockSubscriptionDetailsService.scala, test/services/mocks/MockWhatYearToSignUp.scala, test/views/agent/mocks/MockWhatYearToSignUp.scala
=> ITSASU-1499: Handle save results for tax year selection section

app/controllers/agent/business/OverseasPropertyAccountingMethodController.scala, app/controllers/agent/business/OverseasPropertyCheckYourAnswersController.scala, app/controllers/agent/business/OverseasPropertyStartDateController.scala, app/controllers/agent/business/RemoveOverseasPropertyController.scala, app/controllers/individual/business/OverseasPropertyAccountingMethodController.scala, app/controllers/individual/business/OverseasPropertyCheckYourAnswersController.scala, app/controllers/individual/business/OverseasPropertyStartDateController.scala, app/controllers/individual/business/RemoveOverseasPropertyController.scala, it/connectors/stubs/IncomeTaxSubscriptionConnectorStub.scala, it/controllers/agent/business/OverseasPropertyAccountingMethodControllerISpec.scala, it/controllers/agent/business/OverseasPropertyCheckYourAnswersControllerISpec.scala, it/controllers/agent/business/OverseasPropertyStartDateControllerISpec.scala, it/controllers/agent/business/RemoveOverseasPropertyControllerISpec.scala, it/controllers/agent/business/RemoveUkPropertyControllerISpec.scala, it/controllers/individual/business/OverseasPropertyAccountingMethodControllerISpec.scala, it/controllers/individual/business/OverseasPropertyCheckYourAnswersControllerISpec.scala, it/controllers/individual/business/OverseasPropertyStartDateControllerISpec.scala, it/controllers/individual/business/RemoveOverseasPropertyControllerISpec.scala, it/controllers/individual/business/RemoveUkPropertyControllerISpec.scala, test/controllers/agent/business/OverseasPropertyAccountingMethodControllerSpec.scala, test/controllers/agent/business/OverseasPropertyCheckYourAnswersControllerSpec.scala, test/controllers/agent/business/OverseasPropertyStartDateControllerSpec.scala, test/controllers/agent/business/RemoveOverseasPropertyControllerSpec.scala, test/controllers/individual/business/OverseasPropertyAccountingMethodControllerSpec.scala, test/controllers/individual/business/OverseasPropertyCheckYourAnswersControllerSpec.scala, test/controllers/individual/business/OverseasPropertyStartDateControllerSpec.scala, test/controllers/individual/business/RemoveOverseasPropertyControllerSpec.scala
=> ITSASU-1501: Handle save results for overseas property

test/controllers/individual/business/TaskListControllerSpec.scala, test/models/common/business/BusinessNameModelSpec.scala, test/services/PrePopulationServiceSpec.scala
=> ITSASU-1524: Business Name-Remove Invalid Special Characters

app/models/status/MandationStatus.scala, test/models/status/MandationStatusModelSpec.scala
=> ITSASU-1570: Update mandation status model

app/controllers/agent/TaskListController.scala, app/controllers/agent/ThrottlingController.scala, app/controllers/individual/ThrottlingController.scala, app/controllers/individual/business/TaskListController.scala, app/views/agent/ThrottleEndOfJourney.scala.html, app/views/agent/ThrottleStartOfJourney.scala.html, app/views/individual/ThrottleEndOfJourney.scala.html, app/views/individual/ThrottleStartOfJourney.scala.html, it/controllers/individual/business/TaskListControllerISpec.scala, test/controllers/agent/TaskListControllerSpec.scala, test/controllers/agent/ThrottlingControllerSpec.scala, test/controllers/individual/ThrottlingControllerSpec.scala, test/controllers/individual/business/TaskListControllerSpec.scala
=> ITSASU-1628: Stop checking throttle on the task list show actions

app/views/agent/AgentTaskList.scala.html, app/views/individual/incometax/business/TaskList.scala.html, test/views/agent/AgentTaskListViewSpec.scala, test/views/individual/incometax/business/TaskListViewSpec.scala
=> ITSASU-1732: Fix additional spacing before add a business in task-list page - Mobile version

app/config/featureswitch/FeatureSwitch.scala, app/controllers/individual/subscription/ConfirmationController.scala, app/views/individual/incometax/subscription/SignUpConfirmation.scala.html, it/controllers/individual/subscription/ConfirmationControllerISpec.scala, test/controllers/individual/subscription/ConfirmationControllerSpec.scala, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
=> ITSASU-1822: Sign up - Confirmation page - create page structure

app/views/individual/incometax/subscription/SignUpConfirmation.scala.html, conf/messages, conf/messages.cy, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
=> ITSASU-1824: Sign up - Confirmation page - Add section headers (Next tax year)

app/views/individual/incometax/subscription/SignUpConfirmation.scala.html, conf/messages, conf/messages.cy, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
=> ITSASU-1835: Sign up - Confirmation page - Add "Check HMRC online services" section (Next tax year)

app/models/UpdateDeadlineDates.scala, app/views/agent/SignUpComplete.scala.html, app/views/helpers/injected/UpdateDeadlineTable.scala.html, app/views/individual/incometax/subscription/SignUpComplete.scala.html, app/views/individual/incometax/subscription/SignUpConfirmation.scala.html, conf/messages, conf/messages.cy, test/utilities/ViewSpec.scala, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
=> ITSASU-1829: Sign up - Confirmation page - Quarterly updates section (Next tax year)

app/auth/individual/IncomeTaxSAUser.scala, app/controllers/individual/subscription/ConfirmationController.scala, app/views/individual/incometax/subscription/SignUpConfirmation.scala.html, conf/messages, conf/messages.cy, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
=> ITSASU-1830: Sign up - Confirmation page - Header content (Current Tax Year)

app/views/individual/incometax/subscription/SignUpConfirmation.scala.html, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
=> ITSASU-1830: Fix vertical line bug

app/views/templates/PrincipalMainTemplate.scala.html, test/config/MockConfig.scala, test/views/ServiceNameViewSpec.scala
=> ITSASU-1969: Fix service name

app/forms/agent/AccountingYearForm.scala, app/forms/individual/business/AccountingYearForm.scala, conf/messages, conf/messages.cy, test/forms/agent/AccountingYearFormSpec.scala, test/forms/individual/business/AccountingYearFormSpec.scala, test/utilities/MessagesWrapper.scala, test/utilities/ViewSpec.scala, test/views/agent/ClientDetailsViewSpec.scala, test/views/agent/WhatIncomeSourceToSignUpViewSpec.scala, test/views/agent/business/ClientRemoveUkPropertyViewSpec.scala, test/views/agent/business/OverseasPropertyAccountingMethodViewSpec.scala, test/views/agent/business/OverseasPropertyStartDateViewSpec.scala, test/views/agent/business/RemoveBusinessViewSpec.scala, test/views/agent/business/RemoveClientOverseasPropertyViewSpec.scala, test/views/agent/business/UkPropertyAccountingMethodViewSpec.scala, test/views/agent/business/UkPropertyStartDateViewSpec.scala, test/views/agent/business/WhatYearToSignUpViewSpec.scala, test/views/individual/incometax/business/OverseasPropertyStartDateViewSpec.scala, test/views/individual/incometax/business/RemoveBusinessViewSpec.scala, test/views/individual/incometax/business/RemoveOverseasPropertyViewSpec.scala, test/views/individual/incometax/business/UkPropertyStartDateViewSpec.scala, test/views/individual/incometax/business/WhatYearToSignUpViewSpec.scala, test/views/individual/incometax/incomesource/WhatIncomeSourceToSignUpViewSpec.scala
=> ITSASU-1984: Introduce custom messages test

app/utilities/AccountingPeriodUtil.scala, app/views/agent/SignUpConfirmation.scala.html, conf/messages, conf/messages.cy, test/utilities/AccountingPeriodUtilSpec.scala, test/views/agent/SignUpConfirmationViewSpec.scala, test/views/individual/incometax/subscription/SignUpConfirmationViewSpec.scala
Relates to:
- ITSASU-1927
- ITSASU-1928
- ITSASU-1931
- ITSASU-1932
- ITSASU-1933
- ITSASU-1934
=> ITSASU-ConfirmationFixes - fixed dates, tweaked and added tests.

app/config/frontendAppConfig.scala, app/controllers/agent/eligibility/CannotSignUpThisYearController.scala, app/controllers/agent/matching/ConfirmClientController.scala, app/views/agent/eligibility/CannotSignUpThisYear.scala.html, conf/agent.routes, conf/messages, conf/messages.cy, it/controllers/agent/eligibility/CannotSignUpThisYearControllerISpec.scala, it/helpers/agent/ComponentSpecBase.scala, test/config/MockConfig.scala, test/controllers/agent/eligibility/CannotSignUpThisYearControllerSpec.scala, test/controllers/agent/matching/ConfirmClientControllerSpec.scala, test/views/agent/business/ClientRemoveUkPropertyViewSpec.scala, test/views/agent/eligibility/CannotSignUpThisYearViewSpec.scala
=> ITSASU-1997: create Agent Control List Kick-out pages

app/common/Constants.scala, app/controllers/agent/TaskListController.scala, app/controllers/agent/eligibility/CannotSignUpThisYearController.scala, app/controllers/agent/matching/ConfirmClientController.scala, app/models/Eligibility.scala, app/models/common/TaskListModel.scala, app/services/SubscriptionDetailsService.scala, app/utilities/SubscriptionDataKeys.scala, it/controllers/agent/TaskListControllerISpec.scala, it/helpers/IntegrationTestModels.scala, project/plugins.sbt, test/controllers/agent/TaskListControllerSpec.scala, test/controllers/agent/matching/ConfirmClientControllerSpec.scala, test/models/EligibilitySpec.scala, test/services/mocks/MockSubscriptionDetailsService.scala, test/views/ServiceNameViewSpec.scala
Will be rebased after 2012,1998 are merged.
=> Fetch eligibility by year and check if edit will be permitted.

app/controllers/agent/matching/ConfirmClientController.scala, app/controllers/individual/eligibility/CannotSignUpThisYearController.scala, app/controllers/usermatching/HomeController.scala, app/services/MandationStatusService.scala, app/views/agent/eligibility/CannotSignUpThisYear.scala.html, app/views/individual/eligibility/CannotSignUpThisYear.scala.html, build.sbt, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/individual/eligibility/CannotSignUpThisYearControllerISpec.scala, it/helpers/ComponentSpecBase.scala, project/AppDependencies.scala, test/controllers/usermatching/HomeControllerSpec.scala, test/services/MandationStatusServiceSpec.scala, test/services/mocks/MockMandationStatusService.scala, test/views/individual/eligibility/CannotSignUpThisYearViewSpec.scala
Still requires Welsh translation for the continue button, which has been raised as a separate card https://jira.tools.tax.service.gov.uk/browse/ITSASU-2120
=> [ITSASU-2080] Implement 'Cannot sign up this year' page

app/controllers/agent/WhatYouNeedToDoController.scala, app/views/agent/WhatYouNeedToDo.scala.html, conf/messages, conf/messages.cy, test/controllers/agent/AgentWhatYouNeedToDoControllerSpec.scala, test/views/agent/AgentWhatYouNeedToDoViewSpec.scala
- Passed all required flags through to the view for future work
- Added content switches within the view based on the flags, new content can be placed within the already created sections
- Added tests + test sections + message sections again for future work to simply add the necessary detail they need
=> ITSASU-2179 - Updated agent what you need to do page content

app/views/agent/ThrottleEndOfJourney.scala.html, app/views/agent/ThrottleStartOfJourney.scala.html, app/views/individual/ThrottleEndOfJourney.scala.html, app/views/individual/ThrottleStartOfJourney.scala.html, conf/messages, conf/messages.cy, scripts/start, test/assets/MessageLookup.scala, test/views/individual/ThrottleStartOfJourneyIndividualViewSpec.scala
Updated individual and agent Start of Journey throttling content
=> ITSASU-2277 Throttling content change at the start of journey

app/views/templates/GovUkWrapper.scala.html, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/utilities/ViewSpec.scala, test/views/agent/AgentWhatYouNeedToDoViewSpec.scala, test/views/agent/SignUpCompleteViewSpec.scala, test/views/agent/WhatIncomeSourceToSignUpViewSpec.scala, test/views/agent/business/ClientRemoveUkPropertyViewSpec.scala, test/views/agent/business/OverseasPropertyCheckYourAnswersViewSpec.scala, test/views/agent/business/OverseasPropertyStartDateViewSpec.scala, test/views/agent/business/PropertyCheckYourAnswersViewSpec.scala, test/views/agent/business/RemoveClientOverseasPropertyViewSpec.scala, test/views/agent/business/UkPropertyStartDateViewSpec.scala, test/views/individual/WhatYouNeedToDoSpec.scala, test/views/individual/incometax/business/OverseasPropertyCheckYourAnswersViewSpec.scala, test/views/individual/incometax/business/PropertyCheckYourAnswersViewSpec.scala, test/views/individual/incometax/incomesource/WhatIncomeSourceToSignUpViewSpec.scala
This reverts commit 0b48cc093d66316fcf5d75485206c69b268bb09e.
=> Revert "ITSASU-2329 - Update dependencies and resolve issues"

app/config/featureswitch/FeatureSwitch.scala, app/config/featureswitch/FeatureSwitching.scala, app/controllers/individual/business/PropertyCheckYourAnswersController.scala, app/controllers/individual/business/UkPropertyCountController.scala, app/forms/individual/business/UkPropertyCountForm.scala, app/forms/validation/Constraints.scala, app/models/common/PropertyModel.scala, app/services/PrePopulationService.scala, app/services/SubscriptionDetailsService.scala, app/views/individual/incometax/business/UkPropertyCount.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/individual/business/UkPropertyCountControllerISpec.scala, it/controllers/individual/incomesource/YourIncomeSourceToSignUpControllerISpec.scala, it/helpers/ComponentSpecBase.scala, it/helpers/CustomMatchers.scala, it/helpers/IntegrationTestModels.scala, test/controllers/individual/business/PropertyCheckYourAnswersControllerSpec.scala, test/controllers/individual/business/UkPropertyCountControllerSpec.scala, test/controllers/individual/incomesource/YourIncomeSourceToSignUpControllerSpec.scala, test/forms/individual/business/UkPropertyCountFormSpec.scala, test/models/common/TaskListModelSpec.scala, test/services/PrePopulationServiceSpec.scala, test/views/agent/AgentTaskListViewSpec.scala, test/views/individual/incometax/business/TaskListViewSpec.scala, test/views/individual/incometax/business/UkPropertyCountViewSpec.scala, test/views/individual/incometax/incomesource/YourIncomeSourceToSignUpViewSpec.scala
- Added new page with form, tests, integration tests
- Updated property model to include count
- Updated complete logic on the uk property check your answers to incorporate the new count field when the feature switch is enabled
=> ITSASU-2444 - Added the uk properties count page

app/controllers/agent/business/OverseasPropertyStartDateController.scala, conf/messages, conf/messages.cy, test/controllers/agent/business/OverseasPropertyStartDateControllerSpec.scala, test/views/agent/business/OverseasPropertyStartDateViewSpec.scala
i Please enter the commit message for your changes. Lines starting
=> [ITSASU-2489] - Foreign property content change and back link update
